package com.android.pos.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.android.pos.dao.Merchant;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MERCHANT.
*/
public class MerchantDao extends AbstractDao<Merchant, Long> {

    public static final String TABLENAME = "MERCHANT";

    /**
     * Properties of entity Merchant.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RefId = new Property(1, String.class, "refId", false, "REF_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Type = new Property(3, String.class, "type", false, "TYPE");
        public final static Property Address = new Property(4, String.class, "address", false, "ADDRESS");
        public final static Property Telephone = new Property(5, String.class, "telephone", false, "TELEPHONE");
        public final static Property ContactName = new Property(6, String.class, "contactName", false, "CONTACT_NAME");
        public final static Property ContactTelephone = new Property(7, String.class, "contactTelephone", false, "CONTACT_TELEPHONE");
        public final static Property ContactEmail = new Property(8, String.class, "contactEmail", false, "CONTACT_EMAIL");
        public final static Property LoginId = new Property(9, String.class, "loginId", false, "LOGIN_ID");
        public final static Property PrinterType = new Property(10, String.class, "printerType", false, "PRINTER_TYPE");
        public final static Property PrinterAddress = new Property(11, String.class, "printerAddress", false, "PRINTER_ADDRESS");
        public final static Property PrinterMiniFont = new Property(12, String.class, "printerMiniFont", false, "PRINTER_MINI_FONT");
        public final static Property PrinterLineSize = new Property(13, Integer.class, "printerLineSize", false, "PRINTER_LINE_SIZE");
        public final static Property PrinterRequired = new Property(14, String.class, "printerRequired", false, "PRINTER_REQUIRED");
        public final static Property PrinterFooter = new Property(15, String.class, "printerFooter", false, "PRINTER_FOOTER");
        public final static Property PrintingOption = new Property(16, String.class, "printingOption", false, "PRINTING_OPTION");
        public final static Property Password = new Property(17, String.class, "password", false, "PASSWORD");
        public final static Property PeriodStart = new Property(18, java.util.Date.class, "periodStart", false, "PERIOD_START");
        public final static Property PeriodEnd = new Property(19, java.util.Date.class, "periodEnd", false, "PERIOD_END");
        public final static Property PriceTypeCount = new Property(20, Integer.class, "priceTypeCount", false, "PRICE_TYPE_COUNT");
        public final static Property PriceLabel1 = new Property(21, String.class, "priceLabel1", false, "PRICE_LABEL1");
        public final static Property PriceLabel2 = new Property(22, String.class, "priceLabel2", false, "PRICE_LABEL2");
        public final static Property PriceLabel3 = new Property(23, String.class, "priceLabel3", false, "PRICE_LABEL3");
        public final static Property DiscountType = new Property(24, String.class, "discountType", false, "DISCOUNT_TYPE");
        public final static Property OrderType = new Property(25, String.class, "orderType", false, "ORDER_TYPE");
        public final static Property PaymentType = new Property(26, String.class, "paymentType", false, "PAYMENT_TYPE");
        public final static Property TaxPercentage = new Property(27, Float.class, "taxPercentage", false, "TAX_PERCENTAGE");
        public final static Property ServiceChargePercentage = new Property(28, Float.class, "serviceChargePercentage", false, "SERVICE_CHARGE_PERCENTAGE");
        public final static Property IsLogin = new Property(29, Boolean.class, "isLogin", false, "IS_LOGIN");
        public final static Property Status = new Property(30, String.class, "status", false, "STATUS");
        public final static Property Locale = new Property(31, String.class, "locale", false, "LOCALE");
        public final static Property SecurityQuestion = new Property(32, String.class, "securityQuestion", false, "SECURITY_QUESTION");
        public final static Property SecurityAnswer = new Property(33, String.class, "securityAnswer", false, "SECURITY_ANSWER");
        public final static Property UploadStatus = new Property(34, String.class, "uploadStatus", false, "UPLOAD_STATUS");
        public final static Property CreateBy = new Property(35, String.class, "createBy", false, "CREATE_BY");
        public final static Property CreateDate = new Property(36, java.util.Date.class, "createDate", false, "CREATE_DATE");
        public final static Property UpdateBy = new Property(37, String.class, "updateBy", false, "UPDATE_BY");
        public final static Property UpdateDate = new Property(38, java.util.Date.class, "updateDate", false, "UPDATE_DATE");
    };

    private DaoSession daoSession;


    public MerchantDao(DaoConfig config) {
        super(config);
    }
    
    public MerchantDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MERCHANT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'REF_ID' TEXT," + // 1: refId
                "'NAME' TEXT NOT NULL ," + // 2: name
                "'TYPE' TEXT," + // 3: type
                "'ADDRESS' TEXT," + // 4: address
                "'TELEPHONE' TEXT," + // 5: telephone
                "'CONTACT_NAME' TEXT," + // 6: contactName
                "'CONTACT_TELEPHONE' TEXT," + // 7: contactTelephone
                "'CONTACT_EMAIL' TEXT," + // 8: contactEmail
                "'LOGIN_ID' TEXT," + // 9: loginId
                "'PRINTER_TYPE' TEXT," + // 10: printerType
                "'PRINTER_ADDRESS' TEXT," + // 11: printerAddress
                "'PRINTER_MINI_FONT' TEXT," + // 12: printerMiniFont
                "'PRINTER_LINE_SIZE' INTEGER," + // 13: printerLineSize
                "'PRINTER_REQUIRED' TEXT," + // 14: printerRequired
                "'PRINTER_FOOTER' TEXT," + // 15: printerFooter
                "'PRINTING_OPTION' TEXT," + // 16: printingOption
                "'PASSWORD' TEXT," + // 17: password
                "'PERIOD_START' INTEGER," + // 18: periodStart
                "'PERIOD_END' INTEGER," + // 19: periodEnd
                "'PRICE_TYPE_COUNT' INTEGER," + // 20: priceTypeCount
                "'PRICE_LABEL1' TEXT," + // 21: priceLabel1
                "'PRICE_LABEL2' TEXT," + // 22: priceLabel2
                "'PRICE_LABEL3' TEXT," + // 23: priceLabel3
                "'DISCOUNT_TYPE' TEXT," + // 24: discountType
                "'ORDER_TYPE' TEXT," + // 25: orderType
                "'PAYMENT_TYPE' TEXT," + // 26: paymentType
                "'TAX_PERCENTAGE' REAL," + // 27: taxPercentage
                "'SERVICE_CHARGE_PERCENTAGE' REAL," + // 28: serviceChargePercentage
                "'IS_LOGIN' INTEGER," + // 29: isLogin
                "'STATUS' TEXT," + // 30: status
                "'LOCALE' TEXT," + // 31: locale
                "'SECURITY_QUESTION' TEXT," + // 32: securityQuestion
                "'SECURITY_ANSWER' TEXT," + // 33: securityAnswer
                "'UPLOAD_STATUS' TEXT," + // 34: uploadStatus
                "'CREATE_BY' TEXT," + // 35: createBy
                "'CREATE_DATE' INTEGER," + // 36: createDate
                "'UPDATE_BY' TEXT," + // 37: updateBy
                "'UPDATE_DATE' INTEGER);"); // 38: updateDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MERCHANT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Merchant entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String refId = entity.getRefId();
        if (refId != null) {
            stmt.bindString(2, refId);
        }
        stmt.bindString(3, entity.getName());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(5, address);
        }
 
        String telephone = entity.getTelephone();
        if (telephone != null) {
            stmt.bindString(6, telephone);
        }
 
        String contactName = entity.getContactName();
        if (contactName != null) {
            stmt.bindString(7, contactName);
        }
 
        String contactTelephone = entity.getContactTelephone();
        if (contactTelephone != null) {
            stmt.bindString(8, contactTelephone);
        }
 
        String contactEmail = entity.getContactEmail();
        if (contactEmail != null) {
            stmt.bindString(9, contactEmail);
        }
 
        String loginId = entity.getLoginId();
        if (loginId != null) {
            stmt.bindString(10, loginId);
        }
 
        String printerType = entity.getPrinterType();
        if (printerType != null) {
            stmt.bindString(11, printerType);
        }
 
        String printerAddress = entity.getPrinterAddress();
        if (printerAddress != null) {
            stmt.bindString(12, printerAddress);
        }
 
        String printerMiniFont = entity.getPrinterMiniFont();
        if (printerMiniFont != null) {
            stmt.bindString(13, printerMiniFont);
        }
 
        Integer printerLineSize = entity.getPrinterLineSize();
        if (printerLineSize != null) {
            stmt.bindLong(14, printerLineSize);
        }
 
        String printerRequired = entity.getPrinterRequired();
        if (printerRequired != null) {
            stmt.bindString(15, printerRequired);
        }
 
        String printerFooter = entity.getPrinterFooter();
        if (printerFooter != null) {
            stmt.bindString(16, printerFooter);
        }
 
        String printingOption = entity.getPrintingOption();
        if (printingOption != null) {
            stmt.bindString(17, printingOption);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(18, password);
        }
 
        java.util.Date periodStart = entity.getPeriodStart();
        if (periodStart != null) {
            stmt.bindLong(19, periodStart.getTime());
        }
 
        java.util.Date periodEnd = entity.getPeriodEnd();
        if (periodEnd != null) {
            stmt.bindLong(20, periodEnd.getTime());
        }
 
        Integer priceTypeCount = entity.getPriceTypeCount();
        if (priceTypeCount != null) {
            stmt.bindLong(21, priceTypeCount);
        }
 
        String priceLabel1 = entity.getPriceLabel1();
        if (priceLabel1 != null) {
            stmt.bindString(22, priceLabel1);
        }
 
        String priceLabel2 = entity.getPriceLabel2();
        if (priceLabel2 != null) {
            stmt.bindString(23, priceLabel2);
        }
 
        String priceLabel3 = entity.getPriceLabel3();
        if (priceLabel3 != null) {
            stmt.bindString(24, priceLabel3);
        }
 
        String discountType = entity.getDiscountType();
        if (discountType != null) {
            stmt.bindString(25, discountType);
        }
 
        String orderType = entity.getOrderType();
        if (orderType != null) {
            stmt.bindString(26, orderType);
        }
 
        String paymentType = entity.getPaymentType();
        if (paymentType != null) {
            stmt.bindString(27, paymentType);
        }
 
        Float taxPercentage = entity.getTaxPercentage();
        if (taxPercentage != null) {
            stmt.bindDouble(28, taxPercentage);
        }
 
        Float serviceChargePercentage = entity.getServiceChargePercentage();
        if (serviceChargePercentage != null) {
            stmt.bindDouble(29, serviceChargePercentage);
        }
 
        Boolean isLogin = entity.getIsLogin();
        if (isLogin != null) {
            stmt.bindLong(30, isLogin ? 1l: 0l);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(31, status);
        }
 
        String locale = entity.getLocale();
        if (locale != null) {
            stmt.bindString(32, locale);
        }
 
        String securityQuestion = entity.getSecurityQuestion();
        if (securityQuestion != null) {
            stmt.bindString(33, securityQuestion);
        }
 
        String securityAnswer = entity.getSecurityAnswer();
        if (securityAnswer != null) {
            stmt.bindString(34, securityAnswer);
        }
 
        String uploadStatus = entity.getUploadStatus();
        if (uploadStatus != null) {
            stmt.bindString(35, uploadStatus);
        }
 
        String createBy = entity.getCreateBy();
        if (createBy != null) {
            stmt.bindString(36, createBy);
        }
 
        java.util.Date createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindLong(37, createDate.getTime());
        }
 
        String updateBy = entity.getUpdateBy();
        if (updateBy != null) {
            stmt.bindString(38, updateBy);
        }
 
        java.util.Date updateDate = entity.getUpdateDate();
        if (updateDate != null) {
            stmt.bindLong(39, updateDate.getTime());
        }
    }

    @Override
    protected void attachEntity(Merchant entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Merchant readEntity(Cursor cursor, int offset) {
        Merchant entity = new Merchant( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // refId
            cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // type
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // address
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // telephone
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // contactName
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // contactTelephone
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // contactEmail
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // loginId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // printerType
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // printerAddress
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // printerMiniFont
            cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13), // printerLineSize
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // printerRequired
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // printerFooter
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // printingOption
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // password
            cursor.isNull(offset + 18) ? null : new java.util.Date(cursor.getLong(offset + 18)), // periodStart
            cursor.isNull(offset + 19) ? null : new java.util.Date(cursor.getLong(offset + 19)), // periodEnd
            cursor.isNull(offset + 20) ? null : cursor.getInt(offset + 20), // priceTypeCount
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // priceLabel1
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // priceLabel2
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // priceLabel3
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // discountType
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // orderType
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // paymentType
            cursor.isNull(offset + 27) ? null : cursor.getFloat(offset + 27), // taxPercentage
            cursor.isNull(offset + 28) ? null : cursor.getFloat(offset + 28), // serviceChargePercentage
            cursor.isNull(offset + 29) ? null : cursor.getShort(offset + 29) != 0, // isLogin
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // status
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // locale
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // securityQuestion
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // securityAnswer
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // uploadStatus
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // createBy
            cursor.isNull(offset + 36) ? null : new java.util.Date(cursor.getLong(offset + 36)), // createDate
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // updateBy
            cursor.isNull(offset + 38) ? null : new java.util.Date(cursor.getLong(offset + 38)) // updateDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Merchant entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRefId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.getString(offset + 2));
        entity.setType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAddress(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTelephone(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setContactName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setContactTelephone(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setContactEmail(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setLoginId(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPrinterType(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setPrinterAddress(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setPrinterMiniFont(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setPrinterLineSize(cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13));
        entity.setPrinterRequired(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setPrinterFooter(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setPrintingOption(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setPassword(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setPeriodStart(cursor.isNull(offset + 18) ? null : new java.util.Date(cursor.getLong(offset + 18)));
        entity.setPeriodEnd(cursor.isNull(offset + 19) ? null : new java.util.Date(cursor.getLong(offset + 19)));
        entity.setPriceTypeCount(cursor.isNull(offset + 20) ? null : cursor.getInt(offset + 20));
        entity.setPriceLabel1(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setPriceLabel2(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setPriceLabel3(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setDiscountType(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setOrderType(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setPaymentType(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setTaxPercentage(cursor.isNull(offset + 27) ? null : cursor.getFloat(offset + 27));
        entity.setServiceChargePercentage(cursor.isNull(offset + 28) ? null : cursor.getFloat(offset + 28));
        entity.setIsLogin(cursor.isNull(offset + 29) ? null : cursor.getShort(offset + 29) != 0);
        entity.setStatus(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setLocale(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setSecurityQuestion(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setSecurityAnswer(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setUploadStatus(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setCreateBy(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setCreateDate(cursor.isNull(offset + 36) ? null : new java.util.Date(cursor.getLong(offset + 36)));
        entity.setUpdateBy(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setUpdateDate(cursor.isNull(offset + 38) ? null : new java.util.Date(cursor.getLong(offset + 38)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Merchant entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Merchant entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
